# Generated by Django 5.2.12 on 2026-03-20 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Název filmu')),
                ('length', models.IntegerField(default=90, validators=[django.core.validators.MinValueValidator(45), django.core.validators.MaxValueValidator(200)], verbose_name='Délka v minutách')),
                ('is_for_adults', models.BooleanField(default=False, verbose_name='Pouze pro dospělé')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Popis')),
                ('rating', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Hodnocení')),
            ],
        ),
    ]
