# Generated by Django 5.2.12 on 2026-03-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Název písničky')),
                ('length', models.FloatField(verbose_name='Délka v min')),
                ('author', models.CharField(max_length=50, verbose_name='Autor')),
                ('description', models.FloatField(verbose_name='Popis')),
                ('rating', models.FloatField(verbose_name='Rating')),
                ('is_popular', models.BooleanField(verbose_name='Je populární?')),
            ],
        ),
    ]
