# Generated by Django 5.2.12 on 2026-03-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='description',
            field=models.CharField(max_length=50, verbose_name='Popis'),
        ),
    ]
