# Generated by Django 5.2.12 on 2026-03-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Křestní jméno')),
                ('second_name', models.CharField(max_length=50, verbose_name='Přijmení')),
                ('email', models.CharField(max_length=50, verbose_name='E-mail')),
            ],
        ),
    ]
